version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: thinky_db
      MYSQL_ROOT_PASSWORD: 1997
    volumes:
      - ./tmp/db:/var/lib/mysql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/thinky
    ports:
      - "3000:3000"
    depends_on:
      - db
