version: "3"
services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: "thinky_development"
      MYSQL_ROOT_PASSWORD: "1997"
    volumes:
      - mysql-data:/var/lib/mysql/data
    ports:
      - 3306:3306
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/thinky
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  mysql-data: {}
